server:
  port: 8089
spring:
  application:
    name: insight-gateway
  cloud:
    gateway:
      routes:
        - id: test1
          uri: lb://service-a
          predicates:
            - Path=/service-a/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
      username: nacos
      password: nacos
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        heartbeat:
#          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8189}/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.thalossphere:
      debug
