server:
  port: 8085
spring:
  application:
    name: service-c
  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        heartbeat:
#          enabled: true
    nacos:
      config:
        file-extension: yaml
        server-addr: localhost:8848
#    zookeeper:
#      connect-string: 127.0.0.1:2181
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8189}/eureka/
#    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
      username: nacos
      password: nacos
flowsphere:
  instantInitEnabled: true